version: '3'
services: 
  mongodb:
    container_name: mern-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Mount the volume for MongoDB data  

  backend:
    container_name: mern-backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - URL=mongodb://mongodb/mern
    depends_on:
      - mongodb
    volumes:
      - backend-data:/usr/src/app/data  # Mount the volume for backend data (adjust the path as needed)


  frontend:
    container_name: mern-frontend
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/usr/src/app/data  # Mount the volume for frontend data (adjust the path as needed)

volumes:
  mongo-data:
  backend-data:
  frontend-data:

